version: '2'
services:
    node-exporter:
        image: quay.io/prometheus/node-exporter:latest
        command:
            # NOTE: disable os-release collector; would only report the container
            # OS, rather than balenaOS of the host
            - '--no-collector.os'
            # NOTE: disable filesystem collectors
            - '--no-collector.btrfs'
            - '--no-collector.xfs'
            - '--no-collector.zfs'
        network_mode: host
        labels:
            io.balena.features.sysfs: 1
            io.balena.features.procfs: 1
